title: 'Global Settings'
sections:
  main:
    display: Main
    fields:
      -
        handle: nav_logo
        field:
          container: assets
          mode: grid
          restrict: false
          allow_uploads: true
          max_files: 1
          type: assets
          localizable: false
          listable: hidden
          display: 'Nav Logo'
